name: altair_intro
channels:
dependencies:
  - python=3.8.3
  - pip:
    - altair==4.1.0
    - altair-saver==0.5.0
    - gcsfs==0.7.1
    - google-auth-oauthlib==0.4.1
    - ipykernel==5.3.4
    - ipython==7.18.1
    - jupyterlab==2.2.8
    - numpy==1.19.4
    - pandas==1.1.3

